server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: profile
          uri: http://localhost:8881
          predicates:
            - Path=/api/profile/**
          filters:
            - StripPrefix=1
