services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: keycloak
    depends_on:
      - postgresql
    command: [ "start-dev"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

  postgresql:
    image: postgres:17.2-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak
    networks:
      - app-network

  kafka:
    image: 'bitnami/kafka:3.9.0'
    container_name: kafka
    hostname: kafka
    ports:
      - "29093:29093"
      - "29092:29092"
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - app-network

  akhq:
    image: tchiotludo/akhq:0.25.1
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: 'kafka:9092'
    ports:
      - "8089:8080"
    depends_on:
      - kafka
    networks:
      - app-network

  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    restart: always
    command: ["redis-server", "--requirepass", "admin"]
    ports:
      - '6379:6379'
    networks:
      - app-network

  mongo:
    image: mongo:8.0.3-noble
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: softz-network
